### ISSUE TITLE
OSXCollector Output Filters also import Foundation making it impossible to run on non-Mac machine

### ISSUE THREAD

**Issue by jjsendor** [Yelp/osxcollector#105]
I have run analyze filter on *nix machine and got the following:
```shell
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/nail/home/jsendor/pg/osxcollector/osxcollector/output_filters/analyze.py", line 35, in <module>
    from osxcollector.output_filters.chrome.find_extensions import FindExtensionsFilter as ChromeExtensionsFilter
  File "osxcollector/output_filters/chrome/find_extensions.py", line 6, in <module>
    from osxcollector.osxcollector import DictUtils
  File "osxcollector/osxcollector.py", line 42, in <module>
    import Foundation
ImportError: No module named Foundation
```

Output Filters should not import anything from `osxcollector/osxcollector.py` as it makes them impossible to run on non-Mac machines that do not provide Foundation.

**Comment by jjsendor** [comment]
Actually the only dependency from the main `osxcollector.py` module in the Output Filters is `DictUtils` class.
