### ISSUE TITLE
ConnectionError: Request to https://www.virustotal.com/vtapi/v2/file/report had an empty response

### ISSUE THREAD

**Issue by bfrizb** [Yelp/osxcollector#109]
TypeError: __init__() got an unexpected keyword argument 'server_hostname'
<Greenlet at 0x109d8d050: <bound method AsyncRequest.send of <grequests.AsyncRequest object at 0x109d8f290>>(stream=False)> failed with TypeError

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Volumes/YelpFiles/Code_Yelp/osxcollector/osxcollector/output_filters/analyze.py", line 453, in <module>
    main()
  File "/Volumes/YelpFiles/Code_Yelp/osxcollector/osxcollector/output_filters/analyze.py", line 449, in main
    run_filter_main(AnalyzeFilter)
  File "osxcollector/output_filters/base_filters/output_filter.py", line 140, in run_filter_main
    _run_filter(output_filter, input_stream=fp_in)
  File "osxcollector/output_filters/base_filters/output_filter.py", line 114, in _run_filter
    final_blobs = output_filter.end_of_lines()
  File "osxcollector/output_filters/base_filters/chain.py", line 69, in end_of_lines
    return self._on_end_of_lines(self._head_of_chain)
  File "osxcollector/output_filters/base_filters/chain.py", line 88, in _on_end_of_lines
    final_lines = self._on_end_of_lines(link._next_link)
  File "osxcollector/output_filters/base_filters/chain.py", line 88, in _on_end_of_lines
    final_lines = self._on_end_of_lines(link._next_link)
  File "osxcollector/output_filters/base_filters/chain.py", line 88, in _on_end_of_lines
    final_lines = self._on_end_of_lines(link._next_link)
  File "osxcollector/output_filters/base_filters/chain.py", line 88, in _on_end_of_lines
    final_lines = self._on_end_of_lines(link._next_link)
  File "osxcollector/output_filters/base_filters/chain.py", line 83, in _on_end_of_lines
    for blob in link.end_of_lines():
  File "osxcollector/output_filters/base_filters/threat_feed.py", line 105, in end_of_lines
    self._add_threat_info_to_blobs()
  File "osxcollector/output_filters/base_filters/threat_feed.py", line 115, in _add_threat_info_to_blobs
    all_threat_info = self._lookup_iocs(self.ioc_set)
  File "osxcollector/output_filters/virustotal/lookup_hashes.py", line 34, in _lookup_iocs
    reports = vt.get_file_reports(all_iocs)
  File "/Library/Python/2.7/site-packages/threat_intel/util/http.py", line 353, in wrapper
    result = fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/threat_intel/virustotal.py", line 41, in get_file_reports
    response_chunks = self._request_reports("resource", resource_chunks, 'file/report')
  File "/Library/Python/2.7/site-packages/threat_intel/virustotal.py", line 287, in _request_reports
    return self._requests.multi_get(self.BASE_DOMAIN + endpoint_name, query_params=params)
  File "/Library/Python/2.7/site-packages/threat_intel/util/http.py", line 144, in multi_get
    return self._multi_request(MultiRequest._VERB_GET, urls, query_params, None, to_json=to_json)
  File "/Library/Python/2.7/site-packages/threat_intel/util/http.py", line 340, in _multi_request
    all_responses.extend(self._wait_for_response(requests, to_json))
  File "/Library/Python/2.7/site-packages/threat_intel/util/http.py", line 296, in _wait_for_response
    raise ConnectionError('Request to {0} had an empty response'.format(request.url))
requests.exceptions.ConnectionError: Request to https://www.virustotal.com/vtapi/v2/file/report had an empty response

**Comment by bfrizb** [comment]
This was caused by a mistake on my side. Closing Issue.
